heat_template_version: 2013-05-23

description: >
  Heat WordPress template for Cisco Partner Cloud Rotation

parameters:

  key_name:
    type: string
    description: Name of a KeyPair to enable SSH access to the instance
    default: wordpress
    constraints:
        - allowed_values: [Hunterks_KeyPair, wordpress]
  instance_type:
    type: string
    description: Instance type for WordPress server
    default: Small
    constraints:
        - allowed_values: [t2.nano, Small, Standard, Large]
  image_id:
    type: string
    description: >
     Using a CentOS 7 image for the wordpress deployment
    default: CentOS 7 Cloud
    constraints:
        - allowed_values: [CentOS 7 Cloud, RancherOS]
  Sec_Group:
    type: string
    description: Security Group to use for the Wordpress Server
    default: Hunterks Security group
  public_net:
    type: string
    description: External Network
    default: External

  db_name:
    type: string
    description: WordPress database name
    default: wordpress
    constraints:
      - length: { min: 1, max: 64 }
        description: db_name must be between 1 and 64 characters
      - allowed_pattern: '[a-zA-Z][a-zA-Z0-9]*'
        description: >
          db_name must begin with a letter and contain only alphanumeric
          characters
  db_username:
    type: string
    description: The WordPress database admin account username
    default: admin
    hidden: true
    constraints:
      - length: { min: 1, max: 16 }
        description: db_username must be between 1 and 16 characters
      - allowed_pattern: '[a-zA-Z][a-zA-Z0-9]*'
        description: >
          db_username must begin with a letter and contain only alphanumeric
          characters
  db_password:
    type: string
    description: The WordPress database admin account password
    default: admin
    hidden: true
    constraints:
      - length: { min: 1, max: 41 }
        description: db_password must be between 1 and 41 characters
      - allowed_pattern: '[a-zA-Z0-9]*'
        description: db_password must contain only alphanumeric characters
  db_root_password:
    type: string
    description: Root password for MySQL
    default: admin
    hidden: true
    constraints:
      - length: { min: 1, max: 41 }
        description: db_root_password must be between 1 and 41 characters
      - allowed_pattern: '[a-zA-Z0-9]*'
        description: db_root_password must contain only alphanumeric characters

resources:
  private_net:
        type: OS::Neutron::Net
        properties:
          name: Local

  private_subnet:
        type: OS::Neutron::Subnet
        properties:
          network_id: { get_resource: private_net }
          cidr: 192.168.50.0/24
          gateway_ip: 192.168.50.1
          dns_nameservers: ["8.8.8.8"]
  router1:
        type: OS::Neutron::Router
        properties:
          external_gateway_info:
                network: External

  router1_interface:
        type: OS::Neutron::RouterInterface
        properties:
          router_id: { get_resource: router1 }
          subnet_id: { get_resource: private_subnet }

  server1_port:
        type: OS::Neutron::Port
        properties:
          network_id: { get_resource: private_net }
          security_groups: [ get_param: Sec_Group ]
          fixed_ips:
                - subnet_id: { get_resource: private_subnet }

  server1_floating_ip:
        type: OS::Neutron::FloatingIP
        properties:
          floating_network_id: { get_param: public_net }
          port_id: { get_resource: server1_port }

  wordpress_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      key_name: { get_param: key_name }
      networks:
      - port: {get_resource: server1_port}


      user_data:
        str_replace:
          template: |
            #!/bin/bash -v
            
            sudo su
            curl -fsSL https://get.docker.com/ | sh

            yum -y install docker-engine

            systemctl disable firewalld
            systemctl enable docker.service
            systemctl start docker.service
            chkconfig docker on
            sed -i 's/SELINUX=.*/SELINUX=disabled/' /etc/selinux/config
            systemctl start docker.service
            echo "docker run --name wordpressdb -e MYSQL_ROOT_PASSWORD=db_password -e MYSQL_DATABASE=db_name -d mysql:5.7" | /bin/bash
            docker pull wordpress
            echo "docker run -e WORDPRESS_DB_PASSWORD=db_password -d --name wordpress --link wordpressdb:mysql -p 80:80 -v "$PWD/":/var/www/html  wordpress" | /bin/bash



            
          params:
            db_rootpassword: { get_param: db_root_password }
            db_name: { get_param: db_name }
            db_user: { get_param: db_username }
            db_password: { get_param: db_password }

outputs:
  WebsiteURL:
    description: URL for Wordpress wiki
    value:
      str_replace:
        template: http://host/wordpress
        params:
          host: { get_attr: [wordpress_instance, first_address] }